[options]
addons_path = /proj_edi_odoo,/usr/lib/python3/dist-packages/odoo/addons,/usr/lib/python3/dist-packages/addons
server_wide_modules = web,queue_job

workers = 0
max_cron_threads = 0
proxy_mode = False
without_demo = True
list_db = False

http_interface = 127.0.0.1
http_port = 8090

log_level = info
