[options]
addons_path = /proj_edi_odoo,/usr/lib/python3/dist-packages/odoo/addons,/usr/lib/python3/dist-packages/addons
server_wide_modules = web,queue_job

workers = 4
max_cron_threads = 1
proxy_mode = True
without_demo = True

http_interface = 0.0.0.0
http_port = 8069

log_level = info

[queue_job]
channels = root:1,root.edi:1,root.edi.api:1,root.edi.file:1
