{
    "name": "Financial Base",
    "summary": "Base cadastros and parameters for financial modules",
    "version": "19.0.1.0.0",
    "category": "Accounting",
    "license": "LGPL-3",
    "author": "Sursum Corda",
    "depends": [
        "base",
    ],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/financial_title_species_data.xml",
        "views/menu.xml",
        "views/financial_title_species_views.xml",
        "views/financial_check_return_reason_views.xml",
        "views/financial_portador_views.xml",
        "views/financial_withholding_code_views.xml",
        "views/financial_payment_method_views.xml",
        "views/financial_modality_views.xml",
        "views/financial_history_views.xml",
        "views/financial_movement_reason_views.xml",
        "views/financial_parameter_views.xml",
        "views/res_partner_views.xml",
    ],
    "installable": True,
    "application": False,
}
