from . import financial_history
from . import financial_modality
from . import financial_movement_reason
from . import financial_parameter
from . import financial_payment_method
from . import financial_portador
from . import financial_title_species
from . import financial_withholding_code
from . import res_partner
